#!/usr/bin/ruby
# encoding: utf-8

puts "\n"
puts "I'm sorry! This executable has been DEPRECATED.\n"
puts "Please, from now on do this way...\n\n"
puts "\t./teuton " + ARGV.join(' ').to_s
puts "\n"
puts "Thank you!"
puts "TEUTON\n\n"
