#!/usr/bin/ruby
# encoding: utf-8

require 'rainbow'

require_relative 'lib/application'
require_relative 'lib/project'

def show_help
  puts "Usage:  #{$0} OPTIONS\n\n"
  puts "Options:"
  puts "\t"+Rainbow("create PATH/TO/FILE/FOO").bright+" "+"=> Create new FOO project."
  puts "\t"+" "*27+"Example: #{$0} create check/demo/foo"
  puts "\t"+Rainbow("lab    PATH/TO/FILE/FOO").bright+" "+"=> Show laboratory script objectives on screen."
  puts "\t"+" "*27+"Example: #{$0} lab check/demo/foo.rb"
  puts "\t"+Rainbow("help").bright+" "*20+"=> Show this help."
  puts "\t"+Rainbow("version").bright+" "*17+"=> Show the program version."
  puts "\t"+Rainbow("PATH/TO/FILE.rb").bright+" "*9+"=> Run activity script file."
  puts "\t"+" "*27+"Example: #{$0} check/demo/foor.rb"
  puts ""
end

def show_version
  app=Application.instance
  t = Rainbow(app.name).color(:green)+" (version "+Rainbow(app.version).color(:blue)+")"
  puts t
end

if ARGV.count==0 then
  puts "Usage: #{$0} help"
elsif ['h','-h','help','--help'].include?(ARGV.first) then
  show_help
elsif ['v','-v','version','--version'].include?(ARGV[0]) then
  show_version
elsif ['c','-c','create','--create'].include?(ARGV[0]) then
  Project::create(ARGV[1])
elsif ['l','-l','lab','--lab'].include?(ARGV[0]) then
  Project::laboratory(ARGV[1]) #UNDER DEVELOPMENT
else
  Project::run(ARGV.first)
end


