# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME = "teuton-opensuse"
Vagrant.configure("2") do |config|
  config.vm.define NAME do |i|
    i.vm.box = "generic/opensuse15"
    i.vm.hostname = NAME
    # i.vm.network "public_network", bridge: [ "eth0" ]
    # i.vm.network "public_network", bridge: [ "wlan0" ]
    i.vm.network :forwarded_port, guest: 22, host: 2222
    i.vm.network :forwarded_port, guest: 22, host: 2231
    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", inline: <<-SHELL
      zypper refresh
      zypper in -y vim tree nmap
      zypper in -y neofetch lsb-release

      gem install teuton

      echo "========================================="
      echo "[INFO] Find teuton command"
      find /usr/lib64/ruby/ -name teuton
      echo "[INFO] Create symbolic link to /usr/local/bin/teuton"

      lsb_release -d
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = NAME
      v.memory = 2048
    end
  end
end
