# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME = "debian1"
USERNAME = "user1"

Vagrant.configure("2") do |config|
  config.vm.define NAME do |i|
    i.vm.box = "generic/debian12"
    i.vm.hostname = NAME
    # i.vm.synced_folder "./", "/vagrant"
    # config.vm.network :private_network, ip :"192.168.56.10"
    # i.vm.network "public_network", bridge: ["wlan0"], ip: "192.168.1.201"
    i.vm.network "public_network", ip: "192.168.1.201"
    i.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y tree vim
      useradd #{USERNAME} -m
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = NAME
      v.memory = 2048
    end
  end
end
