# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "teuton-debian" do |i|
    i.vm.box = "generic/debian9"
    i.vm.hostname = "teuton-debian"
    i.vm.network "public_network", bridge: [
      "wlp1s0",
      "enp2s0",
    ]

    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", inline: <<-SHELL
      apt-get install -y tree vim
      apt-get install -y ruby
      gem install teuton
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'teuton-debian'
      v.memory = 2048
    end
  end
end
