# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME = "teuton-fedora"
Vagrant.configure("2") do |config|
  config.vm.define NAME do |i|
    i.vm.box = "generic/fedora38"
    i.vm.hostname = NAME
    # i.vm.network "public_network", bridge: [ "eth0" ]
    # i.vm.network "public_network", bridge: [ "wlan0" ]
    i.vm.network :forwarded_port, guest: 22, host: 2241
    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", path: "install-teuton-mv.sh"
    i.vm.provider "virtualbox" do |v|
      v.name = NAME
      v.memory = 2048
    end
  end
end
